### PR TITLE
added myself as a learner

### PR DESCRIPTION
**Pull request by se-prashant**
I have made a change(added my name and git profile-img) in index.html.

### CODE REVIEW

**Comment by Baba-Yaga-1** [comment]
I have made a change(added my profile name and link of github) in index.html

**Review by rohan-kulkarni-25 — APPROVED** [review]
Great Work !!

**Comment by se-prashant** [comment]
> Great Work !!

> Thanks :)

**Comment by rohan-kulkarni-25** [comment]
Please Feel Free to Start the repository @se-prashant

**Pull request merged**
