### PR TITLE
Demo title PR

### LINKED ISSUE #30: Learner Addition
Enter Details Below !

Github Username :-Nicks-tech
Your Name :-Nandani Paliwal

Thanks !!!

### PR DESCRIPTION
**Pull request by Nandani-Paliwal**
fixes #30

### CODE REVIEW

**Review by rohan-kulkarni-25 — CHANGES_REQUESTED** [review]
You have to add this in an index.html

**Review by rohan-kulkarni-25 — APPROVED** [review]
Done !! Great Work !!

**Comment by Nandani-Paliwal** [comment]
> 
> 
> Done !! Great Work !!

but it was showing that PR run failed

**Comment by rohan-kulkarni-25** [comment]
> 
> 
> > Done !! Great Work !!
> 
> but it was showing that PR run failed

That was github actions don't  worry !

**Comment by Nandani-Paliwal** [comment]
Ok

**Pull request merged**
